services:
  narou:
    build:
      context: .
      dockerfile: dockerfile
      args:
        NAROU_VERSION: 3.9.1
        UID: 1000
        GID: 1000
    image: narou:3.9.1
    command: ["narou", "web", "-np", "33000"]
    volumes:
      - type: bind
        source: .
        target: /home/narou/novel
    tty: true
    stdin_open: true
    ports:
      - 9200:33000
      - 9201:33001
